### ISSUE TITLE
Update packet pathing to account for non-friendly devices

### ISSUE THREAD

**Issue by nnickodem** [nnickodem/NetworkDomination#70]
As a player, I don't want the pathing to route my packet through an enemy device as that packet would be lost.

**Comment by T0YMAK3R** [comment]
Thought:  Create spanning tree for each device, for each device being a root.  Make it so that enemy devices can not be internal (that is, they can be the final destination, but can not be on the path)
Potential issue: Players should be able to pass through enemy controlled switches (as long as they stay on the same VLAN), routers (with negative router effect), and firewalls (with router affect as well as packet loss).
That only leaves PCs and Servers, which should be end-devices anyway.
Instead, perhaps adding a weight for firewalls and routers and create a weighted spanning tree.  Then for switches, it should be checking the VLAN to determine if final destination is valid.

**Comment by T0YMAK3R** [comment]
Tying with issue #69 , we could use time of travel between devices as weight for that path, and then do shortest path on a weighted graph.
